FactoryGirl.define do 
  factory :event do
    organization "MyString"
    name "MyString"
    phone "MyString"
    email "MyString"
    organization_address "MyString"
    organization_address2 "MyString"
    organization_city "MyString"
    organization_state "MyString"
    organization_zip "MyString"
    organization_country "MyString"
    website "MyString"
    event_type "MyString"
    theme "MyText"
    starts_at "2050-08-31"
    ends_at "2050-09-01"
    estimated_attendance "1"
    other_speakers "MyString"
    budget_for_additional_traveller "false"
    housing "MyString"
    bethel_students "false"
    bethel_students_total "1"
    bethel_student_housing "false"
    location_name "MyString"
    address "MyString"
    address2 "MyString"
    city "MyString"
    state "MyString"
    zip "MyString"
    country "MyString"
    information "MyText"
    airport "MyString"
    status "new"
  end
end
